// src/devtools.vue
<script setup lang="ts">
import fontPickerHTML from "url:./panels/network/index.html"

chrome.devtools.panels.create(
  "Network Extra",
  null,
  // See: https://github.com/PlasmoHQ/plasmo/issues/106#issuecomment-1188539625
  fontPickerHTML.split("/").pop(),
)
</script>

<template>
</template>

<style scoped lang="scss">
</style>

// devtools.tsx
import fontPickerHTML from "url:./panels/network/index.html"

chrome.devtools.panels.create(
  "Network Extra",
  null,
  // See: https://github.com/PlasmoHQ/plasmo/issues/106#issuecomment-1188539625
  fontPickerHTML.split("/").pop(),
)

function IndexDevtools() {
  return (
    <h2>
      Welcome to your <a href="https://www.plasmo.com">Plasmo</a> Extension!
    </h2>
  )
}

export default IndexDevtools
